# Generated by Django 4.1 on 2022-08-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('users', '0002_remove_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='base.client'),
        ),
    ]
