# Generated by Django 4.1 on 2022-08-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_name_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="email", field=models.EmailField(max_length=255),
        ),
    ]
