version: '3'

services:
  web:
    # build:
    #   context:.
    #   dockerfile: Dockerfile
    image: web
    container_name: web
    hostname: web
    restart: always
    command: python/code/manage.py runserver 0.0.0.0:8000
    volumes:
      -.:/web
    ports:
      -"8000:8000"
    depends_on:
      -mysql  

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      -3306: 3306
    volumes:
      -./db:/var/lib/mysql
    environment:
      -MYSQL_HOST=localhost 
      -MYSQL_PORT=3306 
      -MYSQL_DATABASE=question_portal
      -MYSQL_USER=root
      -MYSQL_PASSWORD=root
      -MYSQL_ROOT_PASSWORD=root

