# Generated by Django 4.1 on 2022-08-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_date', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('interview_date', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.mentor')),
            ],
        ),
    ]
