# Generated by Django 4.1 on 2022-08-25 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_remove_user_name_user_first_name_user_last_name"),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Interviewee",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("interview_date", models.CharField(max_length=255)),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.category"
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("users.user",),
        ),
        migrations.AddField(
            model_name="client",
            name="requirement_id",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="QuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.category"
                    ),
                ),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.client"
                    ),
                ),
                (
                    "Interviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.interviewee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "Question_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.questionset",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.category"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interviewee",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="base.client"
            ),
        ),
        migrations.AddField(
            model_name="interviewee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
