# Generated by Django 4.1 on 2022-09-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="assesment", name="mentor",),
    ]
