# Generated by Django 4.1 on 2022-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Selected"),
                    ("2", "Rejected"),
                    ("3", "Waiting for feedback"),
                    ("4", "Waiting for Kickstart"),
                    ("5", "Waiting for schedule"),
                    ("6", "Assigned"),
                ],
                max_length=255,
            ),
        ),
    ]
