# Generated by Django 4.1 on 2022-08-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_interviewee_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="Category", new_name="Technology",),
        migrations.RenameField(
            model_name="technology",
            old_name="category_name",
            new_name="Technology_name",
        ),
    ]
