# Generated by Django 4.1 on 2022-08-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_client_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                default=2.34,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.category",
            ),
            preserve_default=False,
        ),
    ]
