# Generated by Django 4.1 on 2022-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_question_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(max_length=20)),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
