# Generated by Django 4.1 on 2022-08-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_category_technology_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewee", old_name="Category", new_name="Technology",
        ),
        migrations.RenameField(
            model_name="question", old_name="category", new_name="Technology",
        ),
        migrations.RenameField(
            model_name="questionset", old_name="Category", new_name="Technology",
        ),
    ]
