# Generated by Django 4.1 on 2022-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_assignment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Selected", "Selected"),
                    ("Rejected", "Rejected"),
                    ("Waiting for feedback", "Waiting for feedback"),
                    ("Waiting for Kickstart", "Waiting for Kickstart"),
                    ("Waiting for schedule", "Waiting for schedule"),
                    ("Assigned", "Assigned"),
                ],
                max_length=255,
            ),
        ),
    ]
