# Generated by Django 4.1 on 2022-09-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_interviewee_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewee",
            name="category_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.category",
            ),
        ),
        migrations.AlterField(
            model_name="interviewee",
            name="interview_date",
            field=models.DateField(max_length=255, null=True),
        ),
    ]
